services:
  postgis:
    build:
      context: db/.
    environment:
      - POSTGRES_USER=${FLOW_DATABASE_USER}
      - POSTGRES_PASSWORD=${FLOW_DATABASE_PASSWORD}
      - POSTGRES_DB=${FLOW_DATABASE_NAME}
      - TARGET_DATABASE_USER=${TARGET_DATABASE_USER}
      - TARGET_DATABASE_PASSWORD=${TARGET_DATABASE_PASSWORD}
      - TARGET_DATABASE_NAME=${TARGET_DATABASE_NAME}
      - TARGET_DATABASE_PORT=${TARGET_DATABASE_PORT}
      - TARGET_DATABASE_HOST=${TARGET_DATABASE_HOST}
    ports:
      - $FLOW_DATABASE_PORT:5432
    volumes:
      - ./db/pg:/var/lib/postgresql/flow
  gdal:
    build:
      context: gdal/.
    environment:
      POSTGRES_USER: $FLOW_DATABASE_USER
      PGPASSWORD: $FLOW_DATABASE_PASSWORD
      POSTGRES_DB: $FLOW_DATABASE_NAME
    volumes:
      - ./data:/data
      - ./gdal/scripts:/scripts
  minio:
    build:
      context: minio/.
    environment:
      DO_SPACES_ACCESS_KEY: $DO_SPACES_ACCESS_KEY
      DO_SPACES_SECRET_KEY: $DO_SPACES_SECRET_KEY
      DO_SPACES_ENDPOINT: $DO_SPACES_ENDPOINT
    volumes:
      - ./data:/data
      - ./minio/scripts:/scripts
