DROP TABLE IF EXISTS
    agency,
    managing_code,
    borough,
    community_district,
    cbbr_policy_area,
    cbbr_need_group,
    cbbr_need,
    cbbr_request,
    cbbr_option_cascade,
	capital_project,
	capital_project_fund,
	capital_commitment_type,
	capital_project_checkbook,
	agency_budget,
	budget_line,
	capital_commitment,
	capital_commitment_fund
CASCADE
