DROP TABLE IF EXISTS
	borough,
	community_district,
	policy_area,
	needs_group
    CASCADE;


-- Temporary target creation code
CREATE TABLE IF NOT EXISTS policy_area (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text
);

CREATE TABLE IF NOT EXISTS needs_group (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text,
	policy_area_id smallint REFERENCES policy_area(id)
);
-- End Temporary code
