DROP TABLE IF EXISTS
	managing_code,
    agency,
    borough,
	community_district,
	policy_area,
	needs_group,
	need,
	request,
	need_agency,
	need_agency_request,
	agency_needs_group
    CASCADE;

-- Temporary target creation code
CREATE TABLE IF NOT EXISTS policy_area (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text
);

CREATE TABLE IF NOT EXISTS needs_group (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text,
	policy_area_id smallint REFERENCES policy_area(id)
);

CREATE TABLE IF NOT EXISTS agency (
	initials text PRIMARY KEY,
	name text NOT NULL
);

CREATE TABLE IF NOT EXISTS agency_needs_group (
	needs_group_id smallint REFERENCES needs_group(id),
	agency_initials text REFERENCES agency(initials)
);

CREATE TABLE IF NOT EXISTS need (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text
);

CREATE TABLE IF NOT EXISTS need_agency (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	need_id smallint REFERENCES need(id),
	agency_initials text REFERENCES agency(initials)
);

CREATE TABLE IF NOT EXISTS request (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text,
	type text CHECK (type = ANY(ARRAY['Capital', 'Expense']))
);

CREATE TABLE IF NOT EXISTS need_agency_request (
	need_agency_id smallint REFERENCES need_agency(id),
	request_id smallint REFERENCES request(id)
);
-- End Temporary code
