DROP TABLE IF EXISTS
	managing_code,
    agency,
    borough,
    community_district,
    cbbr_policy_area,
    cbbr_need_group,
    cbbr_agency_need_group,
    cbbr_need,
    cbbr_request,
    cbbr_agency_need_request
    CASCADE;

-- Temporary target creation code
CREATE TABLE IF NOT EXISTS cbbr_policy_area (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text
);

CREATE TABLE IF NOT EXISTS cbbr_need_group (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text,
	policy_area_id smallint REFERENCES cbbr_policy_area(id)
);

CREATE TABLE IF NOT EXISTS agency (
	initials text PRIMARY KEY,
	name text NOT NULL
);

CREATE TABLE IF NOT EXISTS cbbr_agency_need_group (
	agency_initials text REFERENCES agency(initials),
	need_group_id smallint REFERENCES cbbr_need_group(id)
);

CREATE TABLE IF NOT EXISTS cbbr_need (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text
);

CREATE TABLE IF NOT EXISTS cbbr_agency_need (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	agency_initials text REFERENCES agency(initials),
	need_id smallint REFERENCES cbbr_need(id)
);

CREATE TABLE IF NOT EXISTS cbbr_request (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text,
	type text CHECK (type = ANY(ARRAY['Capital', 'Expense']))
);

CREATE TABLE IF NOT EXISTS cbbr_agency_need_request (
	agency_need_id smallint REFERENCES cbbr_agency_need(id),
	request_id smallint REFERENCES cbbr_request(id)
);
-- End Temporary code
