DROP TABLE IF EXISTS
    source_facility
CASCADE;

CREATE TABLE IF NOT EXISTS source_facility (
    fac_name text,
    address_num text,
    street_name text,
    address text,
    address_city text,
    zipcode char(5),
    fac_type text,
    fac_sub_group text,
    fac_group text,
    fac_domain text,
    service_area text,
    operator_name text,
    operator_abbreviation text,
    operator_type text,
    overseer_agency text,
    overseer_abbreviation text,
    overseer_level text,
    capacity text,
    capacity_type text,
    borough_name text,
    bin text,
    bbl char(10),
    latitude numeric,
    longitude numeric,
    xcoord numeric,
    ycoord numeric,
    community_district char(3),
    nta_2010 text,
    nta_2020 text,
    council text,
    ct_2010 text,
    ct_2020 text,
    boro_code text,
    school_district char(2),
    police_precinct text,
    datasource text,
    unique_id text,
    wkt geometry(multipoint, 4326)
);
