-- Temporary target creation code
DROP TABLE IF EXISTS
	policy_area
	CASCADE;

CREATE TABLE IF NOT EXISTS policy_area (
	id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text
);
-- End Temporary code
TRUNCATE
	policy_area
	CASCADE;

INSERT INTO policy_area (description)
SELECT DISTINCT
		"Policy Area" AS description
FROM source_community_board_budget_request_options
ORDER BY
		source_community_board_budget_request_options."Policy Area";
