on: [push]

jobs:
    etl:
        runs-on: ubuntu-latest
        services:
            postgis:
                image: postgis/postgis:15-3.4-alpine
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    # Maps tcp port 5432 on service container to the host
                    - 5432:5432
        steps:
            - name: check out repo code
              uses: actions/checkout@v4
            - name: Install prerequisite packages
              run: |
                apt update  
                apt install -y wget
                apt install -y software-properties-common
            - name: Install postgres-client-15
              run: |                
                sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
                wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
                apt update
                apt install -y postgresql-client-15
            - name: Install minio client
              run: |
                wget https://dl.min.io/client/mc/release/linux-amd64/mc
                chmod +x mc
            - name: Install python
              run: |
                apt install -y python3 python3-pip
                pip install -r requirements.txt 
            - name: Install dbt dependencies
              run: |
                apt install -y git
                dbt deps
            